identity-service.port=8081
identity-service.datasource-url=jdbc:mysql://localhost:3307/cis_identity_db_test?createDatabaseIfNotExist=true
identity-service.username=test_user
identity-service.password=test_pass
identity-service.hibernate-ddl-auto=create-drop
identity-service.urlregistry=http://test-eureka:8761/eureka/