identity-service.port=8081
identity-service.datasource-url=jdbc:mysql://prod-db-server:3306/cis_identity_db?useSSL=true
identity-service.username=admin_prod
identity-service.password=MOT_DE_PASSE_SECURISE
identity-service.hibernate-ddl-auto=none
identity-service.urlregistry=http://prod-eureka:8761/eureka/