identity-service.port=8081
spring.datasource-url=jdbc:mysql://mysql-db:3306/cis_identity_db?useSSL=true
spring.datasource.username=admin_prod
spring.datasource.password=MOT_DE_PASSE_SECURISE
identity-service.hibernate-ddl-auto=none
identity-service.urlregistry=http://eureka:8761/eureka/