identity-service.port=8081
# Base de données
spring.datasource-url=jdbc:mysql://mysql-db:3306/cis_identity_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate-ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#identity-service.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect       
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# JWT
identity-service.jwt-secret=CIS_Integration_2026_Secure_Key_For_Identity_Service_ESMT_Dakar_Senegal
identity-service.jwt-expiration=86400000

# MAIL
identity-service.mail-host=smtp.gmail.com
identity-service.mail-port=587
identity-service.mail-username=khadijasadjikms@gmail.com
identity-service.mail-password=oggk iefx qkcc brnd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# Eureka 
identity-service.urlregistry=http://eureka:8761/eureka/

