project_service.port=8082

# Base de données MySQL
#project_service.datasource-url=jdbc:mysql://mysql-db:3306/cis_project_db?createDatabaseIfNotExist=true
#project_service.username=root
#project_service.password=root
spring.datasource.url=jdbc:mysql://mysql-db:3306/cis_project_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# MongoDB
spring.data.mongodb.uri=mongodb://mongodb-db:27017/cis_documents_db

# Eureka 
project_service.urlregistry=http://eureka:8761/eureka/

 
# MAIL
project_service.mail-host=smtp.gmail.com
project_service.mail-port=587
project_service.mail-username=khadijasadjikms@gmail.com
project_service.mail-password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration