gateway.port=8090
gateway.identity-path=/api/auth/**, /api/users/**, /v3/api-docs/**, /swagger-ui/**
gateway.project-path=/api/projects/**,/api/tasks/**,/api/statistiques/**, /v3/api-docs/**, /swagger-ui/**
gateway.urlregistry=http://localhost:8761/eureka/

gateway.identity-path=/api/auth/**, /api/users/**, /identity-service/v3/api-docs
gateway.project-path=/api/projects/**, /api/tasks/**, /api/statistiques/**, /project-service/v3/api-docs

# 1. On active le support de base
springdoc.enable-native-support=true
springdoc.swagger-ui.path=/swagger-ui.html

# 2. On désactive le locator automatique qui pose problème
springdoc.gateway.discovery.locator.enabled=false

# 3. ON FORCE LE MENU DÉROULANT EN DUR (Sans toucher aux microservices !)
springdoc.swagger-ui.urls[0].name=Identity Service
springdoc.swagger-ui.urls[0].url=/identity-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Project Service
springdoc.swagger-ui.urls[1].url=/project-service/v3/api-docs