gateway.port=8090
gateway.identity-path=/api/auth/**, /api/users/**, /v3/api-docs/**, /swagger-ui/**
gateway.project-path=/api/projects/**,/api/tasks/**,/api/statistiques/**, /v3/api-docs/**, /swagger-ui/**
gateway.urlregistry=http://localhost:8761/eureka/

# Active le support natif de la Gateway pour l'agrégation
springdoc.enable-native-support=true
springdoc.swagger-ui.use-root-path=true

# Définition des deux choix du menu déroulant
springdoc.swagger-ui.urls[0].name=Identity Service (Gestion Utilisateurs)
springdoc.swagger-ui.urls[0].url=/api/users/v3/api-docs

springdoc.swagger-ui.urls[1].name=Project Service (Gestion Projets & Tâches)
springdoc.swagger-ui.urls[1].url=/api/projects/v3/api-docs