# gateway.port=8090
# gateway.identity-path=/api/auth/**, /api/users/**, /v3/api-docs/**, /swagger-ui/**
# gateway.project-path=/api/projects/**,/api/tasks/**,/api/statistiques/**, /v3/api-docs/**, /swagger-ui/**
# gateway.urlregistry=http://localhost:8761/eureka/

# gateway.identity-path=/api/auth/**, /api/users/**, /identity-service/v3/api-docs
# gateway.project-path=/api/projects/**, /api/tasks/**, /api/statistiques/**, /project-service/v3/api-docs

# # 1. On active le support de base
# springdoc.enable-native-support=true
# springdoc.swagger-ui.path=/swagger-ui.html

# # 2. On désactive le locator automatique qui pose problème
# springdoc.gateway.discovery.locator.enabled=false

# # 3. ON FORCE LE MENU DÉROULANT EN DUR (Sans toucher aux microservices !)
springdoc.swagger-ui.urls[0].name=Identity Service
# springdoc.swagger-ui.urls[0].url=/identity-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Project Service
# springdoc.swagger-ui.urls[1].url=/project-service/v3/api-docs

gateway.port=8090
gateway.urlregistry=http://localhost:8761/eureka/

# 📂 1. Chemins d'accès de la Gateway (On garde les préfixes pour Swagger)
gateway.identity-path=/api/auth/**, /api/users/**, /identity-service/v3/api-docs
gateway.project-path=/api/projects/**
#, /api/projects/tasks/**, /api/projects/statistiques/**, /project-service/v3/api-docs

# 🤖 2. Route Identity-Service actualisée
spring.cloud.gateway.routes[0].id=identity-service
spring.cloud.gateway.routes[0].uri=lb://identity-service
spring.cloud.gateway.routes[0].predicates[0]=Path=${gateway.identity-path}
# 🪄 Filtre 1 : Supprime le préfixe pour le microservice, Filtre 2 : Nettoie la sécurité
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/identity-service/(?<segment>.*), /$\\{segment}
#spring.cloud.gateway.routes[0].filters[1]=RemoveRequestHeader=Authorization

# 🤖 3. Route Project-Service actualisée
spring.cloud.gateway.routes[1].id=project-service
spring.cloud.gateway.routes[1].uri=lb://project-service
spring.cloud.gateway.routes[1].predicates[0]=Path=${gateway.project-path}
spring.cloud.gateway.routes[1].filters[0]=SetRequestHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
# 🪄 Filtre 1 : Supprime le préfixe pour le microservice, Filtre 2 : Nettoie la sécurité
#spring.cloud.gateway.routes[1].filters[0]=RewritePath=/project-service/(?<segment>.*), /$\\{segment}
#spring.cloud.gateway.routes[1].filters[1]=RemoveRequestHeader=Authorization


# 🚀 4. Configuration Swagger UI inchangée
springdoc.enable-native-support=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Identity Service
springdoc.swagger-ui.urls[0].url=/identity-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Project Service
springdoc.swagger-ui.urls[1].url=/project-service/v3/api-docs