gateway.port=8090
gateway.identity-path=/api/auth/**, /api/users/**, /v3/api-docs/**, /swagger-ui/**
gateway.project-path=/api/projects/**,/api/tasks/**,/api/statistiques/**, /v3/api-docs/**, /swagger-ui/**
gateway.urlregistry=http://localhost:8761/eureka/

gateway.identity-path=/api/auth/**, /api/users/**
gateway.project-path=/api/projects/**, /api/tasks/**, /api/statistiques/**

On active le support natif de la Gateway
springdoc.enable-native-support=true

Découverte automatique des microservices via Eureka (Génère le menu tout seul)
springdoc.swagger-ui.urls-splitter=,
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.gateway.discovery.locator.enabled=true
springdoc.gateway.discovery.locator.id-initializer=true