gateway.port=8090
gateway.identity-path=/api/auth/**, /api/users/**, /v3/api-docs/**, /swagger-ui/**
gateway.project-path=/api/projects/**,/api/tasks/**,api/statistiques/**
gateway.urlregistry=http://localhost:8761/eureka/