gateway.port=80
gateway.identity-path=/api/auth/**, /api/users/**
gateway.project-path=/api/projects/**, /api/projects/tasks/**, /api/projects/statistiques/**, /project-service/v3/api-docs
gateway.urlregistry=http://eureka:8761/eureka/