gateway.port=8091
gateway.identity-path=/api/auth/**, /api/users/**
gateway.project-path=/api/projects/**, /api/tasks/**, /api/projects/statistiques/**, /project-service/v3/api-docs
gateway.urlregistry=http://test-eureka:8761/eureka/